/**
 * Refrigerant saturation-property engine. Single canonical source for Subcooling, Superheat and the PT tool.
 *
 * Data: src/refrigerant/dataset.json (generated by scripts/gen_refrigerant_dataset.py from CoolProp reference EOS).
 *  - rows are [tempF, bubblePsia, dewPsia] on a 1 degF grid; pressures are ABSOLUTE.
 * Pressure basis: technician-facing pressures are PSIG; psig = psia - ATMOSPHERIC_PSI (14.696, standard atmosphere).
 * Interpolation: linear in ln(psia) versus temperature (Clausius-Clapeyron-like curve, error << 0.01 degF on a 1 degF grid).
 * No extrapolation: out-of-range input returns an error result.
 */
import raw from './dataset.json';

export type Branch = 'bubble' | 'dew';
export type RefrigerantId = 'R-22' | 'R-410A' | 'R-32' | 'R-454B' | 'R-407C' | 'R-134a' | 'R-404A';

export interface RefrigerantInfo {
  id: RefrigerantId;
  name: string;
  composition: string;
  ashrae34: string;
  model: string;
  /** dew - bubble temperature at equal pressure (degF) at the 40 degF / 100 degF bubble pressures */
  glideF40: number;
  glideF100: number;
  hasGlide: boolean;
  /** Tabulated saturation-temperature range (bubble curve) in degF */
  tempRangeF: [number, number];
}

export type LookupError =
  | { kind: 'INVALID_INPUT'; message: string }
  | { kind: 'OUT_OF_RANGE'; message: string; min: number; max: number };

export type LookupResult = { ok: true; value: number } | { ok: false; error: LookupError };

interface Row { t: number; lnBubble: number; lnDew: number; bubble: number; dew: number }
interface Dataset { dataset: string; atmosphericPsi: number; coolprop: string; refrigerants: Record<string, {
  id: RefrigerantId; name: string; composition: string; ashrae34: string; model: string; glideF40: number; glideF100: number; rows: number[][];
}> }

const data = raw as unknown as Dataset;

export const ATMOSPHERIC_PSI = data.atmosphericPsi;
export const DATASET_ID = data.dataset;
/** A glide above this (degF) is treated as a meaningful bubble/dew split in the UI. */
export const GLIDE_THRESHOLD_F = 0.5;

export const REFRIGERANT_ORDER: RefrigerantId[] = ['R-22', 'R-410A', 'R-32', 'R-454B', 'R-407C', 'R-134a', 'R-404A'];

const tables = new Map<RefrigerantId, Row[]>();
for (const id of REFRIGERANT_ORDER) {
  tables.set(id, data.refrigerants[id].rows.map(([t, b, d]) => ({ t, bubble: b, dew: d, lnBubble: Math.log(b), lnDew: Math.log(d) })));
}

export const psiaFromPsig = (psig: number) => psig + ATMOSPHERIC_PSI;
export const psigFromPsia = (psia: number) => psia - ATMOSPHERIC_PSI;

export function listRefrigerants(): RefrigerantInfo[] {
  return REFRIGERANT_ORDER.map((id) => getRefrigerant(id));
}

export function getRefrigerant(id: RefrigerantId): RefrigerantInfo {
  const r = data.refrigerants[id];
  const rows = tables.get(id)!;
  return {
    id, name: r.name, composition: r.composition, ashrae34: r.ashrae34, model: r.model,
    glideF40: r.glideF40, glideF100: r.glideF100,
    hasGlide: Math.max(r.glideF40, r.glideF100) >= GLIDE_THRESHOLD_F,
    tempRangeF: [rows[0].t, rows[rows.length - 1].t],
  };
}

const col = (r: Row, b: Branch) => (b === 'bubble' ? r.bubble : r.dew);
const lncol = (r: Row, b: Branch) => (b === 'bubble' ? r.lnBubble : r.lnDew);

/** Supported gauge-pressure range (psig) for a branch. */
export function pressureRangePsig(id: RefrigerantId, branch: Branch): [number, number] {
  const rows = tables.get(id)!;
  return [psigFromPsia(col(rows[0], branch)), psigFromPsia(col(rows[rows.length - 1], branch))];
}

const bad = (message: string): LookupResult => ({ ok: false, error: { kind: 'INVALID_INPUT', message } });
const fmt = (n: number) => (Math.round(n * 10) / 10).toString();

/** Gauge pressure (psig) -> saturation temperature (degF) on the bubble or dew curve. */
export function saturationTempFromPsig(id: RefrigerantId, psig: number, branch: Branch): LookupResult {
  if (!Number.isFinite(psig)) return bad('Pressure must be a number.');
  const rows = tables.get(id)!;
  const [lo, hi] = pressureRangePsig(id, branch);
  const psia = psiaFromPsig(psig);
  if (psia <= 0) return bad('Pressure is below absolute zero.');
  if (psig < lo - 1e-9 || psig > hi + 1e-9) {
    return { ok: false, error: { kind: 'OUT_OF_RANGE', min: lo, max: hi,
      message: `${fmt(psig)} psig is outside the supported range for ${id} (${fmt(lo)} to ${fmt(hi)} psig).` } };
  }
  const lnp = Math.log(psia);
  // rows are strictly increasing in pressure; binary search for the bracketing pair
  let a = 0, b = rows.length - 1;
  while (b - a > 1) {
    const m = (a + b) >> 1;
    if (lncol(rows[m], branch) <= lnp) a = m; else b = m;
  }
  const la = lncol(rows[a], branch), lb = lncol(rows[b], branch);
  const frac = lb === la ? 0 : (lnp - la) / (lb - la);
  return { ok: true, value: rows[a].t + Math.min(1, Math.max(0, frac)) * (rows[b].t - rows[a].t) };
}

/** Saturation temperature (degF) -> gauge pressure (psig) on the bubble or dew curve. */
export function psigFromSaturationTemp(id: RefrigerantId, tempF: number, branch: Branch): LookupResult {
  if (!Number.isFinite(tempF)) return bad('Temperature must be a number.');
  const rows = tables.get(id)!;
  const lo = rows[0].t, hi = rows[rows.length - 1].t;
  if (tempF < lo || tempF > hi) {
    return { ok: false, error: { kind: 'OUT_OF_RANGE', min: lo, max: hi,
      message: `${fmt(tempF)}°F is outside the supported range for ${id} (${lo} to ${hi}°F).` } };
  }
  const i = Math.min(rows.length - 2, Math.floor(tempF - lo));
  const a = rows[i], b = rows[i + 1];
  const frac = (tempF - a.t) / (b.t - a.t);
  const lnp = lncol(a, branch) + frac * (lncol(b, branch) - lncol(a, branch));
  return { ok: true, value: psigFromPsia(Math.exp(lnp)) };
}

/** Raw table rows converted to gauge pressure, for the PT chart view. */
export function tableRows(id: RefrigerantId, stepF = 5): { tempF: number; bubblePsig: number; dewPsig: number }[] {
  return tables.get(id)!.filter((r) => r.t % stepF === 0)
    .map((r) => ({ tempF: r.t, bubblePsig: psigFromPsia(r.bubble), dewPsig: psigFromPsia(r.dew) }));
}

export function rawRows(id: RefrigerantId): readonly { t: number; bubble: number; dew: number }[] {
  return tables.get(id)!;
}

/** Fahrenheit/Celsius helpers (internal data is degF; Celsius UI is future work). */
export const fToC = (f: number) => (f - 32) / 1.8;
export const cToF = (c: number) => c * 1.8 + 32;
